from enum import Enum

class RiskStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ADJUSTED = "ADJUSTED"

class RiskRejectReason(str, Enum):
    NONE = "NONE"
    MAX_DAILY_DRAWDOWN_REACHED = "MAX_DAILY_DRAWDOWN_REACHED"
    MAX_OPEN_POSITIONS_REACHED = "MAX_OPEN_POSITIONS_REACHED"
    SPREAD_TOO_HIGH = "SPREAD_TOO_HIGH"
    INVALID_SL_TP = "INVALID_SL_TP"
    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
    SIGNAL_NEUTRAL = "SIGNAL_NEUTRAL"