from enum import Enum

class TrendRegime(str, Enum):
    TRENDING_BULL = "TRENDING_BULL"
    TRENDING_BEAR = "TRENDING_BEAR"
    RANGING = "RANGING"
    BREAKOUT_POTENTIAL = "BREAKOUT_POTENTIAL"
    TRANSITION = "TRANSITION"
    UNCERTAIN = "UNCERTAIN"

class VolatilityState(str, Enum):
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"
    NORMAL_VOLATILITY = "NORMAL_VOLATILITY"
    EXPANSION = "EXPANSION"
    CONTRACTION = "CONTRACTION"

class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"